Repository jaseci-labs/jaseci, pull requests merged in 2023-03, with the labels that each got.

#919 Prevent access to views that require superuser privilege
  jaseci_studio/.env
  jaseci_studio/.env.jsserv
  jaseci_studio/__e2e__/logs.spec.ts
  jaseci_studio/__tests__/graphSwitcherHooks.test.tsx
  jaseci_studio/mocks/login.handlers.ts
  jaseci_studio/next.config.js
  jaseci_studio/package.json
  jaseci_studio/playwright.config.ts
  jaseci_studio/src/components/ChangeGraphModal.tsx
  jaseci_studio/src/components/LoginForm.tsx
  jaseci_studio/src/components/Navbar.tsx
  jaseci_studio/src/components/ReactQuery.tsx
  jaseci_studio/src/hooks/useGuard.tsx
  jaseci_studio/src/hooks/useUserInfo.tsx
  jaseci_studio/src/pages/actions.tsx
  jaseci_studio/src/pages/architype.tsx
  jaseci_studio/src/pages/graph-viewer/index.tsx
  jaseci_studio/src/pages/index.tsx
  jaseci_studio/src/pages/logs.tsx
  jaseci_studio/yarn.lock
Labels: ready for review

#968 add install command to jaseci_serv setup file
  jaseci_serv/setup.py
  jaseci_studio/export_studio.sh
Labels: ready for review

#981 Canonianalytics Updates
  README.md
  examples/CanoniAnalytics/README.md
  examples/CanoniAnalytics/code/movie_data.json
  examples/CanoniAnalytics/codelabs/1_preparation.md
  examples/CanoniAnalytics/codelabs/7_creating_custom_action_to_scrap_movie_data.md
  examples/CanoniAnalytics/misc/scrapping_example.py
Labels: ready for review

#986 Regex std actions
  README.md
  docs/docs/Developing_with_JAC/Language_Features/actions/regex.md
  jaseci_core/jaseci/__init__.py
  jaseci_core/jaseci/actions/live_actions.py
  jaseci_core/jaseci/actions/standard/regex.py
  jaseci_core/jaseci/actions/standard/tests/fixtures/regex.jac
  jaseci_core/jaseci/actions/standard/tests/test_regex.py
Labels: core, ready for review

#1001 [VSCode] Use default python path if `jac.pythonPath` is not set
  support/vscode_extension/jac/client/src/extension.ts
Labels: ready for review

#1006 test updated to clean created folders.
  jaseci_ai_kit/jac_misc/jac_misc/ph/tests/test_ph.py
  jaseci_ai_kit/jac_nlp/jac_nlp/bi_enc/tests/test_bi_enc.py
  jaseci_ai_kit/jac_nlp/jac_nlp/bi_ner/tests/test_bi_ner.py
  jaseci_ai_kit/jac_nlp/jac_nlp/ent_ext/tests/test_ent_ext.py
  jaseci_ai_kit/jac_nlp/jac_nlp/fast_enc/tests/test_fast_enc.py
  jaseci_ai_kit/jac_nlp/jac_nlp/sbert_sim/tests/test_sbert_sim.py
  jaseci_ai_kit/jac_nlp/jac_nlp/tfm_ner/tests/test_tfm_ner.py
Labels: ready for review

#1000 added paraphraser model
  README.md
  jaseci_ai_kit/.gitignore
  jaseci_ai_kit/README.md
  jaseci_ai_kit/jac_nlp/README.md
  jaseci_ai_kit/jac_nlp/jac_nlp/action_configs/paraphraser_action_config.py
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/README.md
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/__init__.py
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/config.cfg
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/paraphraser.py
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/requirements.txt
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/tests/__init__.py
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/tests/fixtures/__init__.py
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/tests/fixtures/paraphraser.jac
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/tests/test_paraphraser.py
  jaseci_ai_kit/jac_nlp/setup.py
Labels: ready for review, ai_kit

#1009 Add workflow for running jac extension tests
  .github/workflows/jac-extension-test.yml
Labels: ready for review

#1008 Update release action to generate studio files
  .github/workflows/build-and-release.yml
Labels: ready for review

#1036 AI Kit Test Fix
  .github/workflows/jac-misc-test.yml
  .github/workflows/jac-nlp-test.yml
  .github/workflows/jac-speech-test.yml
  .github/workflows/jac-vision-test.yml
  jaseci_ai_kit/jac_misc/jac_misc/ph/tests/fixtures/ph.jac
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/paraphraser.py
  jaseci_ai_kit/jac_nlp/jac_nlp/paraphraser/requirements.txt
  jaseci_ai_kit/jac_speech/jac_speech/stt/stt.py
  jaseci_ai_kit/jac_speech/jac_speech/stt/tests/fixtures/stt.jac
  jaseci_ai_kit/jac_speech/jac_speech/vc_tts/tests/fixtures/vc_tts.jac
  jaseci_ai_kit/jac_vision/jac_vision/detr/tests/fixtures/detr.jac
  jaseci_ai_kit/jac_vision/jac_vision/dpt/tests/fixtures/dpt.jac
  jaseci_ai_kit/jac_vision/jac_vision/rftm/tests/fixtures/rftm.jac
  jaseci_ai_kit/jac_vision/jac_vision/yolos/tests/fixtures/yolos.jac
  jaseci_ai_kit/test.sh
Labels: ai_kit
