Repository jaseci-labs/jaseci, pull requests merged in 2023-02, with the labels that each got.

#849 add context menu to graph viewer
  ui_components/src/components.d.ts
  ui_components/src/components/jsc-app/readme.md
  ui_components/src/components/jsc-button/jsc-button.tsx
  ui_components/src/components/jsc-button/readme.md
  ui_components/src/components/jsc-divider/readme.md
  ui_components/src/components/jsc-graph/graph-context-menu.spec.tsx
  ui_components/src/components/jsc-graph/graph-context-menu.tsx
  ui_components/src/components/jsc-graph/jsc-graph.spec.tsx
  ui_components/src/components/jsc-graph/jsc-graph.tsx
  ui_components/src/components/jsc-graph/readme.md
Labels: ready for review

#876 [Studio] add architypes view
  jaseci_core/jaseci/actor/sentinel.py
  jaseci_core/jaseci/api/architype_api.py
  jaseci_core/jaseci/api/tests/fixtures/test_architype.jac
  jaseci_core/jaseci/api/tests/test_architype_api.py
  jaseci_core/jaseci/jac/ir/ast_builder.py
  jaseci_studio/__tests__/ArchitypeList.test.tsx
  jaseci_studio/__tests__/architypeHooks.test.tsx
  jaseci_studio/__tests__/parseError.test.ts
  jaseci_studio/__tests__/setup/setup.ts
  jaseci_studio/mocks/architype.handlers.ts
  jaseci_studio/mocks/data/architype_list.json
  jaseci_studio/mocks/data/architype_register.json
  jaseci_studio/mocks/handlers.ts
  jaseci_studio/mocks/js_public.handlers.ts
  jaseci_studio/mocks/server.ts
  jaseci_studio/mocks/testQueryClient.ts
  jaseci_studio/mocks/utils.tsx
  jaseci_studio/package.json
  jaseci_studio/src-tauri/src/main.rs
  jaseci_studio/src/components/ArchitypeList.tsx
  jaseci_studio/src/components/Editor.tsx
  jaseci_studio/src/components/LoadedActions.tsx
  jaseci_studio/src/components/Navbar.tsx
  jaseci_studio/src/components/ReactQuery.tsx
  jaseci_studio/src/hooks/useArtchitypeList.ts
  jaseci_studio/src/hooks/useGetActiveSentinel.tsx
  jaseci_studio/src/hooks/useRegisterArchetype.tsx
  jaseci_studio/src/hooks/useStudioEditor.tsx
  jaseci_studio/src/lib/jacLang.ts
  jaseci_studio/src/pages/_app.tsx
  jaseci_studio/src/pages/actions.tsx
  jaseci_studio/src/pages/architype.tsx
  jaseci_studio/yarn.lock
Labels: ready for review

#906 Add support for viewing a user's graph
  jaseci_core/jaseci/api/super_api.py
  jaseci_serv/jaseci_serv/base/models.py
  jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
  jaseci_studio/__tests__/ChangeGraphModal.test.tsx
  jaseci_studio/__tests__/graphSwitcherHooks.test.tsx
  jaseci_studio/mocks/data/detailed_object.json
  jaseci_studio/mocks/data/master_allusers.json
  jaseci_studio/mocks/handlers.ts
  jaseci_studio/mocks/js_admin.handlers.ts
  jaseci_studio/mocks/object.handlers.ts
  jaseci_studio/src/components/ChangeGraphModal.tsx
  jaseci_studio/src/hooks/useGetDetailedObject.ts
  jaseci_studio/src/hooks/useGetMasterAllUsers.tsx
  jaseci_studio/src/pages/graph-viewer/index.tsx
  ui_components/src/components/jsc-graph/graph-context-menu.tsx
  ui_components/src/components/jsc-graph/jsc-graph-context-menu.css
  ui_components/src/components/jsc-graph/jsc-graph.tsx
Labels: ready for review

#939 add ability to set how node groups are displayed
  ui_components/src/components.d.ts
  ui_components/src/components/jsc-app/readme.md
  ui_components/src/components/jsc-graph/graph-context-menu.spec.tsx
  ui_components/src/components/jsc-graph/graph-context-menu.tsx
  ui_components/src/components/jsc-graph/jsc-graph.spec.tsx
  ui_components/src/components/jsc-graph/jsc-graph.tsx
  ui_components/src/components/jsc-graph/mockData/initial_graph_node_view.json
  ui_components/src/components/jsc-graph/readme.md
  ui_components/src/components/jsc-graph/utils.ts
  ui_components/src/components/jsc-select/readme.md
Labels: ready for review

#932 Add tab for running walkers on architype view
  jaseci_studio/__tests__/ArchitypeList.test.tsx
  jaseci_studio/__tests__/RunWalker.test.tsx
  jaseci_studio/mocks/handlers.ts
  jaseci_studio/mocks/walker.handlers.ts
  jaseci_studio/package.json
  jaseci_studio/src/components/ArchitypeList.tsx
  jaseci_studio/src/components/Editor.tsx
  jaseci_studio/src/components/RunWalker.tsx
  jaseci_studio/src/hooks/useRunWalker.tsx
  jaseci_studio/src/pages/architype.tsx
  jaseci_studio/yarn.lock
Labels: ready for review

#946 fix for model load error
  jaseci_ai_kit/jac_nlp/jac_nlp/sbert_sim/sbert_sim.py
Labels: ready for review

#955 added jac built in feature to get unique items from the list
  docs/docs/Language_basics/lists.md
  jaseci_core/jaseci/jac/interpreter/interp.py
  jaseci_core/jaseci/tests/jac_test_progs.py
  jaseci_core/jaseci/tests/test_progs.py
Labels: core, ready for review, new feature/enhancement

#953 Add studio route to jsserv
  jaseci_serv/jaseci_serv/studio/__init__.py
  jaseci_serv/jaseci_serv/studio/tests/__init__.py
  jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/actions.html
  jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/architype.html
  jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/dashboard.html
  jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/graph-viewer.html
  jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/index.html
  jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/logs.html
  jaseci_serv/jaseci_serv/studio/tests/test_studio_routes.py
  jaseci_serv/jaseci_serv/studio/urls.py
  jaseci_serv/jaseci_serv/studio/views.py
  jaseci_serv/jaseci_serv/urls.py
  jaseci_studio/export_studio.sh
  jaseci_studio/format_templates.py
  jaseci_studio/next.config.js
  jaseci_studio/package.json
  jaseci_studio/src-tauri/tauri.conf.json
  jaseci_studio/src/components/ArchitypeList.tsx
  jaseci_studio/src/components/ChangeGraphModal.tsx
  jaseci_studio/src/components/LoginForm.tsx
  jaseci_studio/src/components/LogsViewer/LogsViewer.tsx
  jaseci_studio/src/components/Navbar.tsx
  jaseci_studio/src/components/RunWalker.tsx
  jaseci_studio/src/hooks/useGetMasterAllUsers.tsx
  jaseci_studio/src/pages/_app.tsx
  jaseci_studio/src/pages/architype.tsx
  jaseci_studio/theme.ts
  jaseci_studio/yarn.lock
Labels: ready for review

#952 updates built in str language documentation
  docs/docs/Language_basics/strings.md
Labels: documentation, ready for review

#963 add jsctl studio command to launch studio with authenticated session
  jaseci_core/jaseci/jsctl/jsctl.py
  jaseci_studio/src/components/LoginForm.tsx
  jaseci_studio/src/components/ReactQuery.tsx
Labels: ready for review

#895 canoniAnalytics codelab
  examples/CanoniAnalytics/README.md
  examples/CanoniAnalytics/code/build_graph.jac
  examples/CanoniAnalytics/code/cluster.jac
  examples/CanoniAnalytics/code/movie_data.json
  examples/CanoniAnalytics/code/scrapy.py
  examples/CanoniAnalytics/code/summarization.jac
  examples/CanoniAnalytics/code/text_similarity.jac
  examples/CanoniAnalytics/codelabs/1_preparation.md
  examples/CanoniAnalytics/codelabs/2_map_the_data_to_graph.md
  examples/CanoniAnalytics/codelabs/3_getting_summery_and_keywords_of_pharagraphs.md
  examples/CanoniAnalytics/codelabs/4_find_semantically_similar_sentences.md
  examples/CanoniAnalytics/codelabs/5_clustering_documents.md
  examples/CanoniAnalytics/images/example_location_node_view.PNG
  examples/CanoniAnalytics/images/example_scene_node.PNG
  examples/CanoniAnalytics/images/initial_view_movie_graph.PNG
  examples/CanoniAnalytics/images/initial_view_movie_graph_2.PNG
  examples/CanoniAnalytics/images/jaseci_studio_login.PNG
  examples/CanoniAnalytics/images/keyword_example.PNG
  examples/CanoniAnalytics/images/summerizer_example.PNG
  examples/CanoniAnalytics/misc/scrapping_example.py
  jaseci_ai_kit/jac_misc/jac_misc/cluster/README.md
Labels: documentation, ready for review

#973 added sentiment analysis module
  README.md
  jaseci_ai_kit/README.md
  jaseci_ai_kit/jac_nlp/README.md
  jaseci_ai_kit/jac_nlp/jac_nlp/action_configs/sentiment_action_config.py
  jaseci_ai_kit/jac_nlp/jac_nlp/config.py
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/README.md
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/__init__.py
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/requirements.txt
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/sentiment.py
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/tests/fixtures/__init__.py
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/tests/fixtures/sentiment.jac
  jaseci_ai_kit/jac_nlp/jac_nlp/sentiment/tests/test_sentiment.py
  jaseci_ai_kit/jac_nlp/setup.py
Labels: ready for review, ai_kit
