Repository jaseci-labs/jaseci, pull requests merged in 2025-06, with the labels that each got.

#2005 Switch ability decorators to Sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2006 Update TypedCtxBlock body handling
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2007 Update IfStmt body type
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/tests/test_language.py
Labels: codex

#2010 Switch Except body to use sequences
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2011 Refactor loop statement bodies to sequences
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2013 Switch Assignment target to Sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/def_use_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/main/sym_tab_build_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2018 Refactor GlobalStmt target
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/main/pyjac_ast_link_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2019 Update MatchArch to use sequence patterns
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/tests/test_language.py
Labels: codex

#2021 Modify Enum body to use Sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2014 Refactor FuncSignature params to sequence
  jac-mtllm/mtllm/plugin.py
  jac-mtllm/mtllm/semtable.py
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/def_impl_match_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/main/pyjac_ast_link_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2025 Fix parser AST kid lists
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2027 Refactor parser: remove SubNodeList from with_stmt
  jac/jaclang/compiler/parser.py
Labels: codex

#2029 Refactor decorators to use list
  jac/jaclang/compiler/parser.py
Labels: codex

#2032 Refactor func_decl_params to return list
  jac/jaclang/compiler/parser.py
Labels: codex

#2034 Refactor parser lists
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/def_use_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2035 Refactor inherited_archs parsing
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
Labels: codex

#2036 Refactor parser code_block to use list
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/tests/test_cfg_build_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2046 Refactor assignment list parser
  jac/jaclang/compiler/parser.py
Labels: codex

#2047 Refactor filter compare list parsing
  jac/jaclang/compiler/parser.py
Labels: codex

#2049 Refactor kw_pattern_list parsing
  jac/jaclang/compiler/jac.lark
  jac/jaclang/compiler/parser.py
Labels: codex

#2051 Refactor parser pattern list
  jac/jaclang/compiler/parser.py
Labels: codex

#2045 [VSCE]: Fix : Semantic token colors retain on file change
  jac/jaclang/langserve/engine.jac
  jac/jaclang/langserve/server.jac
  jac/jaclang/langserve/tests/server_test/test_lang_serve.py
Labels: bug, VSCE

#2070 Fix lint issues
  jac/jaclang/compiler/passes/main/type_checker_pass.py
  jac/jaclang/compiler/type_system/diagnostics.py
  jac/jaclang/compiler/type_system/primitive_types.py
  jac/jaclang/compiler/type_system/symbol_table.py
  jac/jaclang/compiler/type_system/type_evaluator.py
  jac/jaclang/compiler/type_system/types.py
Labels: codex

#2062 [VSCE]: Fix: Multi-File SemToken Stability
  jac/jaclang/langserve/engine.jac
  jac/jaclang/langserve/tests/server_test/test_lang_serve.py
  jac/jaclang/langserve/tests/server_test/utils.py
Labels: bug, VSCE

#2100 Enable natural import for language server
  jac/examples/reference/concurrent_expressions.py
  jac/examples/reference/import_include_statements.py
  jac/examples/reference/special_comprehensions.py
  jac/jaclang/__init__.py
  jac/jaclang/cli/cli.py
  jac/jaclang/compiler/tests/fixtures/pkg_import_lib_py/__init__.py
  jac/jaclang/compiler/tests/fixtures/pkg_import_lib_py/sub/__init__.py
  jac/jaclang/langserve/__init__.jac
  jac/jaclang/langserve/tests/server_test/test_lang_serve.py
  jac/jaclang/langserve/tests/server_test/utils.py
  jac/jaclang/langserve/tests/test_sem_tokens.py
  jac/jaclang/langserve/tests/test_server.py
  jac/jaclang/runtimelib/meta_importer.py
Labels: codex

#2152 Semstring implementation for MTLLM
  jac-mtllm/mtllm/plugin.py
  jac-mtllm/mtllm/semtable.py
  jac-mtllm/tests/fixtures/llm_semstrings.jac
  jac-mtllm/tests/test_jaclang.py
  jac/examples/reference/semstrings.jac
  jac/examples/reference/semstrings.md
  jac/examples/reference/semstrings.py
  jac/jaclang/compiler/constant.py
  jac/jaclang/compiler/jac.lark
  jac/jaclang/compiler/larkparse/jac_parser.py
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/__init__.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/sem_def_match_pass.py
  jac/jaclang/compiler/passes/main/sym_tab_build_pass.py
  jac/jaclang/compiler/passes/main/tests/fixtures/sem_def_match.impl.jac
  jac/jaclang/compiler/passes/main/tests/fixtures/sem_def_match.jac
  jac/jaclang/compiler/passes/main/tests/test_sem_def_match_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/program.py
  jac/jaclang/compiler/unitree.py
Labels: ready to review

#2165 Ignore statement removed
  docs/docs/communityhub/breaking_changes.md
  docs/docs/communityhub/release_notes.md
  jac/examples/littleX/littleX.impl.jac
  jac/examples/littleX/littleX_single.jac
  jac/examples/reference/ignore_statements.jac
  jac/examples/reference/ignore_statements.md
  jac/examples/reference/ignore_statements.py
  jac/jaclang/compiler/constant.py
  jac/jaclang/compiler/jac.lark
  jac/jaclang/compiler/larkparse/jac_parser.py
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/def_use_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/tests/fixtures/ignore.jac
  jac/jaclang/tests/fixtures/ignore_dup.jac
Labels: ready to review, jaclang
