Repository jaseci-labs/jaseci, pull requests merged in 2025-05, with the labels that each got.

#1573 Place holder docstrings are removed.
  jac/.flake8
  jac/jaclang/compiler/codeloc.py
  jac/jaclang/compiler/constant.py
  jac/jaclang/compiler/passes/main/access_modifier_pass.py
  jac/jaclang/compiler/passes/main/annex_pass.py
  jac/jaclang/compiler/passes/main/def_use_pass.py
  jac/jaclang/compiler/passes/main/fuse_typeinfo_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pybc_gen_pass.py
  jac/jaclang/compiler/passes/main/pyjac_ast_link_pass.py
  jac/jaclang/compiler/passes/main/sym_tab_build_pass.py
  jac/jaclang/compiler/passes/main/tests/test_sym_tab_build_pass.py
  jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
  jac/jaclang/compiler/passes/tool/tests/test_unparse_validate.py
  jac/jaclang/compiler/passes/uni_pass.py
  jac/jaclang/compiler/unitree.py
Labels: ready to review, jaclang

#1804 Add: Environment discovery and selection for Jac executable in VSCE
  jac/support/vscode_ext/jac/package.json
  jac/support/vscode_ext/jac/src/extension.ts
  jac/support/vscode_ext/jac/src/utils.ts
Labels: VSCE

#1838 Delete issue in jac-cloud
  jac/jaclang/compiler/passes/main/def_use_pass.py
  jac/jaclang/tests/fixtures/del_clean.jac
  jac/jaclang/tests/test_cli.py
Labels: bug, jaclang

#1806 VSCE Run button
  jac/support/vscode_ext/jac/package.json
  jac/support/vscode_ext/jac/src/commands/index.ts
  jac/support/vscode_ext/jac/src/constants.ts
  jac/support/vscode_ext/jac/src/extension.ts
  jac/support/vscode_ext/jac/src/lsp/client.ts
  jac/support/vscode_ext/jac/src/utils.ts
  jac/support/vscode_ext/jac/src/utils/envDetection.ts
  jac/support/vscode_ext/jac/src/utils/jacRunner.ts
  jac/support/vscode_ext/jac/src/webview/visualDebugger.ts
Labels: new feature/enhancement, VSCE

#1880 Improve main README
  README.md
  docs/docs/learn/getting_started.md
Labels: codex

#1881 Improve doc IR formatting
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
Labels: codex

#1883 Fix walrus conversion
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/tests/fixtures/py_namedexpr.py
  jac/jaclang/tests/test_language.py
Labels: codex

#1884 Improve cleanliness of pyast_load_pass
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
Labels: codex

#1886 Auto infer jac_import language
  jac/examples/reference/concurrent_expressions.py
  jac/examples/reference/special_comprehensions.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/runtimelib/machine.py
Labels: codex

#1890 Centralize path inference utilities
  jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/runtimelib/machine.py
  jac/jaclang/utils/__init__.py
  jac/jaclang/utils/module_resolver.py
Labels: codex

#1870 [add] test coverage for jaclang langserver
  .github/workflows/test-jaseci.yml
  jac/jaclang/langserve/engine.py
  jac/jaclang/langserve/server.py
  jac/jaclang/langserve/tests/server_test/code_test.py
  jac/jaclang/langserve/tests/server_test/test_lang_serve.py
  jac/jaclang/langserve/tests/server_test/utils.py
  jac/pytest.ini
  pytest.ini
Labels: VSCE

#1906 Expand Jac in a Flash tutorial
  docs/docs/learn/jac_in_a_flash.md
Labels: codex

#1907 Split guess game impls
  docs/docs/learn/introduction.md
  docs/docs/learn/jac_in_a_flash.md
  docs/mkdocs.yml
  jac/examples/guess_game/guess_game4.impl.jac
  jac/examples/guess_game/guess_game4.jac
  jac/examples/guess_game/guess_game5.impl.jac
  jac/examples/guess_game/guess_game5.jac
  jac/jaclang/langserve/tests/test_server.py
Labels: codex

#1911 Populate introduction sections
  docs/docs/learn/introduction.md
Labels: codex

#1923 Fix mermaid diagrams in lets_build
  docs/docs/internals/planning_specs/native_type_system/lets_build.md
Labels: codex

#1939 Fix reference doc headings
  jac/examples/reference/arithmetic_expressions.md
  jac/examples/reference/assert_statements.md
  jac/examples/reference/atom.md
  jac/examples/reference/atomic_expressions.md
  jac/examples/reference/atomic_pipe_back_expressions.md
  jac/examples/reference/base_module_structure.md
  jac/examples/reference/bitwise_expressions.md
  jac/examples/reference/builtin_types.md
  jac/examples/reference/check_statements.md
  jac/examples/reference/collection_values.md
  jac/examples/reference/concurrent_expressions.md
  jac/examples/reference/connect_expressions.md
  jac/examples/reference/context_managers.md
  jac/examples/reference/data_spatial_spawn_expressions.md
  jac/examples/reference/delete_statements.md
  jac/examples/reference/disengage_statements.md
  jac/examples/reference/expressions.md
  jac/examples/reference/f_string_tokens.md
  jac/examples/reference/free_code.md
  jac/examples/reference/function_calls.md
  jac/examples/reference/global_and_nonlocal_statements.md
  jac/examples/reference/ignore_statements.md
  jac/examples/reference/implementations.md
  jac/examples/reference/inline_python.md
  jac/examples/reference/introduction.md
  jac/examples/reference/lambda_expressions.md
  jac/examples/reference/lexer_tokens.md
  jac/examples/reference/logical_and_compare_expressions.md
  jac/examples/reference/match_capture_patterns.md
  jac/examples/reference/match_class_patterns.md
  jac/examples/reference/match_litteral_patterns.md
  jac/examples/reference/match_mapping_patterns.md
  jac/examples/reference/match_patterns.md
  jac/examples/reference/match_sequence_patterns.md
  jac/examples/reference/match_singleton_patterns.md
  jac/examples/reference/match_statements.md
  jac/examples/reference/pipe_back_expressions.md
  jac/examples/reference/raise_statements.md
  jac/examples/reference/references_(unused).md
  jac/examples/reference/report_statements.md
  jac/examples/reference/return_statements.md
  jac/examples/reference/special_comprehensions.md
  jac/examples/reference/tests.md
  jac/examples/reference/try_statements.md
  jac/examples/reference/visit_statements.md
  jac/examples/reference/walrus_assignments.md
  jac/examples/reference/while_statements.md
  jac/examples/reference/yield_statements.md
Labels: codex

#1944 Fix comment syntax in Jac reference docs
  jac/examples/reference/check_statements.md
  jac/examples/reference/context_managers.md
  jac/examples/reference/control_statements.md
  jac/examples/reference/data_spatial_spawn_expressions.md
  jac/examples/reference/data_spatial_typed_context_blocks.md
  jac/examples/reference/disengage_statements.md
  jac/examples/reference/free_code.md
  jac/examples/reference/function_calls.md
  jac/examples/reference/lambda_expressions.md
  jac/examples/reference/match_statements.md
  jac/examples/reference/raise_statements.md
  jac/examples/reference/return_statements.md
  jac/examples/reference/tests.md
  jac/examples/reference/try_statements.md
  jac/examples/reference/while_statements.md
  jac/examples/reference/yield_statements.md
Labels: codex

#1945 Add missing manual features to reference docs
  docs/mkdocs.yml
  jac/examples/reference/builtin_types.md
  jac/examples/reference/functions_and_abilities.md
  jac/examples/reference/import_include_statements.md
  jac/examples/reference/introduction.md
  jac/examples/reference/lexer_tokens.md
  jac/examples/reference/logical_and_compare_expressions.md
  jac/examples/reference/names_and_references.md
Labels: codex

#1964 Fix header hierarchy in Jac coding manual
  docs/docs/learn/jac_coding_manual.md
Labels: codex

#1981 Refactor FilterCompr parameter
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1980 Refactor FuncCall params to sequence
  jac-mtllm/mtllm/plugin.py
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/runtimelib/utils.py
Labels: codex

#1984 Update SetVal and ListVal to use sequences
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1985 Refactor TupleVal values to sequence
  jac-mtllm/mtllm/plugin.py
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/runtimelib/utils.py
Labels: codex

#1987 Switch Test.body to sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1989 Change Import item type to Sequence
  docs/docs/internals/symbol_tables/linking.md
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/import_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/main/sym_tab_link_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1990 refactor: use sequence for withstmt exprs
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/utils/tests/test_lang_tools.py
Labels: codex

#1993 Refactor Archetype base_classes handling
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/inheritance_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/langserve/engine.jac
Labels: codex

#1995 refactor: store archetype decorators as sequences
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1996 refactor impl decorators to sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1998 Fix ImplDef.spec to use sequences
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#1999 Refactor ImplDef body to use Sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex

#2002 Refactor Archetype body to use Sequence
  jac/jaclang/compiler/parser.py
  jac/jaclang/compiler/passes/main/def_impl_match_pass.py
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/unitree.py
Labels: codex
