Repository jaseci-labs/jaseci, pull requests merged in 2025-07, with the labels that each got.

#2216 🎯 Semstring are codegenerated to python (this is required to remove SemRegistry)
  jac/jaclang/compiler/passes/main/pyast_gen_pass.py
  jac/jaclang/compiler/passes/main/sem_def_match_pass.py
  jac/jaclang/compiler/passes/main/tests/fixtures/codegen_sem.jac
  jac/jaclang/compiler/passes/main/tests/test_pyast_gen_pass.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/runtimelib/machine.py
Labels: new feature/enhancement

#2343 [VSCE] VisDebug support for windows
  jac/support/vscode_ext/jac/src/commands/index.ts
  jac/support/vscode_ext/jac/src/environment/manager.ts
  jac/support/vscode_ext/jac/src/utils/jacRunner.ts
  jac/support/vscode_ext/jac/src/visual_debugger/visdbg.ts
  jac/support/vscode_ext/jac/src/webview/visualDebugger.ts
Labels: bug, VSCE

#2359 [VSCE] Implement cached environment detection with deeper directory scanning
  jac/support/vscode_ext/jac/package-lock.json
  jac/support/vscode_ext/jac/src/commands/index.ts
  jac/support/vscode_ext/jac/src/constants.ts
  jac/support/vscode_ext/jac/src/environment/manager.ts
  jac/support/vscode_ext/jac/src/utils.ts
  jac/support/vscode_ext/jac/src/utils/envDetection.ts
Labels: new feature/enhancement, VSCE

#2404 🐛 Fix: `by llm` formatter
  jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
  jac/jaclang/compiler/passes/tool/tests/fixtures/simple_walk_fmt.jac
Labels: jaclang

#2418 Refactor PyImporter to load Python modules as Jac AST
  jac/jaclang/cli/cli.py
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/runtimelib/importer.py
  jac/jaclang/tests/fixtures/pyfunc_fstr.py
  jac/jaclang/tests/test_cli.py
  jac/jaclang/utils/module_resolver.py
Labels: jaclang

#2425 Temporary Patch: Avoid Format Failures during py2jac Conversion
  jac/jaclang/cli/cli.py
  jac/jaclang/compiler/unitree.py
  jac/jaclang/tests/fixtures/pyfunc_fmt.py
  jac/jaclang/tests/test_cli.py
Labels: bug, jaclang

#2437 Fix: KWEsc in KWPair handling in py2jac
  jac/jaclang/compiler/passes/main/pyast_load_pass.py
  jac/jaclang/tests/fixtures/pyfunc_kwesc.py
  jac/jaclang/tests/test_cli.py
Labels: bug
